import type { CourseContentMap } from "./types";

export const anzanContent: CourseContentMap = {
  "picture-the-soroban": {
    "what-is-anzan": [
      { type: "heading", text: "Anzan means mental calculation" },
      {
        type: "paragraph",
        text: "Anzan (暗算) is the Japanese word for mental arithmetic. In abacus training it means something more specific: you keep a vivid picture of the soroban in your mind and slide its beads to compute — even when no real abacus is nearby.",
      },
      {
        type: "paragraph",
        text: "Masters move beads so fast on their mental board that they can add a column of fifteen numbers in seconds. That speed is not a gift — it is a trained mental image. This course trains yours, step by step.",
      },
      {
        type: "explore",
        label: "Spend a moment with a real board. This is the exact picture you're about to learn to hold in your head.",
        rods: 4,
        initial: [2, 5, 7, 0],
      },
      {
        type: "paragraph",
        text: "Notice the rods, the amber beam, the red heaven bead and the sky-blue earth beads. Every anzan exercise in this course starts from this picture.",
      },
    ],
    "mental-board": [
      { type: "heading", text: "Build your mental board" },
      {
        type: "paragraph",
        text: "A mental soroban is just three things you can picture: vertical rods (one per digit), an amber beam across the middle, and beads that count only when they touch it.",
      },
      {
        type: "paragraph",
        text: "The rules are exactly the rules of real beads: a heaven bead touching the beam is 5, and each earth bead touching it is 1. Because your mental board follows the same rules, every bead trick you already know transfers straight across.",
      },
      {
        type: "list",
        items: [
          "The units rod is always on the right — anchor it first.",
          "One heaven bead rests above the beam; four earth beads below.",
          "Only beads touching the beam are counted.",
        ],
      },
      {
        type: "explore",
        label: "Build 35, study it for a few seconds, then hit Clear and rebuild it from memory.",
        rods: 2,
        initial: [0, 0],
      },
    ],
    "snap-a-photo": [
      { type: "heading", text: "Photograph the beads" },
      {
        type: "paragraph",
        text: "Anzan starts with seeing: glance at a number on a real board, look away, and describe the beads that were touching the beam. This photo is the raw material your mental board is made from.",
      },
      {
        type: "paragraph",
        text: "Start with one rod, then two. Don't count the beads — read the number the way you read a word.",
      },
      {
        type: "read",
        prompt: "Snap a photo of this rod. What number is it?",
        digits: [8],
        choices: [8, 5, 3, 6],
        explanation: { text: "A heaven bead touching the beam gives you 5, and three earth beads under it add 3 more - the rod is showing 8." },
      },
      {
        type: "read",
        prompt: "One more photo. What number does this board show?",
        digits: [6, 2],
        choices: [26, 62, 20, 24],
        explanation: { text: "Read left to right: the first rod is 6 and the second is 2, so the board shows 62." },
      },
      {
        type: "build",
        prompt: "Now close your eyes, picture that board, and rebuild 26 from memory.",
        target: 26,
        rods: 2,
        explanation: { text: "You just photographed 26, so rebuild it the same way: two earth beads on the tens rod and a heaven bead plus one earth bead on the ones." },
      },
      {
        type: "quiz",
        prompt: "You photograph a rod showing 9, then clear the board. What number are you holding in your mind?",
        choices: [9, 5, 0, 4],
        answer: 9,
        explanation: { text: "The photo lives in your mind, not on the board, so clearing the physical beads does not erase the 9 you are holding." },
      },
    ],
    "image-to-number": [
      { type: "heading", text: "Read your own mind" },
      {
        type: "paragraph",
        text: "The point of the mental photo is to read it back. When you picture a board, name the number from left to right: read the heaven bead of each rod first, then the earth beads beneath it.",
      },
      {
        type: "read",
        prompt: "Read the number your mental board is showing.",
        digits: [5, 1],
        choices: [15, 51, 12, 10],
        explanation: { text: "Left to right: a 5 on the tens rod and a 1 on the ones rod make 51." },
      },
      {
        type: "read",
        prompt: "What about this one?",
        digits: [0, 3],
        choices: [30, 3, 33, 300],
        explanation: { text: "The left rod is empty, so that leading zero is only a place holder - the ones rod shows 3, so the number is 3." },
      },
      {
        type: "read",
        prompt: "Now read a three-rod board.",
        digits: [2, 4, 7],
        choices: [742, 247, 724, 274],
        explanation: { text: "Read each rod left to right: 2 hundreds, 4 tens, and 7 ones make 247." },
      },
      {
        type: "quiz",
        prompt: "Your mental board shows only a heaven bead on the tens rod. What number is that?",
        choices: [50, 5, 10, 15],
        answer: 50,
        explanation: { text: "A single heaven bead on the tens rod means 5 tens, which is 50." },
      },
    ],
    "picture-the-soroban-check": [
      { type: "heading", text: "Level check — picture the soroban" },
      {
        type: "paragraph",
        text: "Hold a number in your mind, read it, and build it. Solve every question to finish the level.",
      },
      {
        type: "read",
        prompt: "What number is your mental board showing?",
        digits: [6],
        choices: [6, 5, 4, 7],
        explanation: { text: "One heaven bead (5) plus one earth bead (1) touching the beam on the units rod is 6." },
      },
      {
        type: "read",
        prompt: "And this one?",
        digits: [0, 4],
        choices: [40, 4, 44, 400],
        explanation: { text: "The left rod is empty, so the 4 on the ones rod is the whole number - 4." },
      },
      {
        type: "build",
        prompt: "Picture 71, then show it on your abacus.",
        target: 71,
        rods: 2,
        explanation: { text: "71 is 7 tens and 1 one, so build a heaven bead plus two earth beads on the tens rod and one earth bead on the ones." },
      },
      {
        type: "quiz",
        prompt: "You hold 84 in mind. What does the tens rod of your picture show?",
        choices: [8, 4, 80, 84],
        answer: 8,
        explanation: { text: "84 has 8 in the tens place, so the tens rod of your picture shows 8." },
      },
    ],
  },

  "mental-addition": {
    "add-without-trading": [
      { type: "heading", text: "Add simple sums in your head" },
      {
        type: "paragraph",
        text: "On a mental board, addition feels exactly like the real thing: slide earth beads toward the beam. Picture 2, slide one more bead up, and you see 3.",
      },
      {
        type: "paragraph",
        text: "These sums never fill a rod past nine, so nothing carries — just keep the running picture simple.",
      },
      {
        type: "quiz",
        prompt: "2 + 1 = ?",
        choices: [3, 2, 4, 5],
        answer: 3,
        explanation: { text: "Slide one more earth bead up to the two already on the rod, and your board shows 3." },
      },
      {
        type: "quiz",
        prompt: "12 + 31 = ?",
        choices: [43, 34, 42, 53],
        answer: 43,
        explanation: { text: "Add rod by rod: 1 ten + 3 tens is 4 tens, and 2 + 1 is 3 ones - so 43." },
      },
      {
        type: "build",
        prompt: "Check your mental picture: show 12 + 31 = 43 on the abacus.",
        target: 43,
        rods: 2,
        explanation: { text: "12 + 31 really is 43, so build 4 tens and 3 ones to confirm your mental addition." },
      },
    ],
    "five-friends": [
      { type: "heading", text: "Friends of five" },
      {
        type: "paragraph",
        text: "When you need more earth beads than are free, use the friends-of-five trick: add 5 by dropping the heaven bead, then take away the addend's friend of five. Four's friend is one; three's friend is two.",
      },
      {
        type: "paragraph",
        text: "So 3 + 4 becomes: drop the five, remove one. Watch your mental board settle on 7.",
      },
      {
        type: "quiz",
        prompt: "3 + 4 = ?",
        choices: [7, 6, 5, 9],
        answer: 7,
        explanation: { text: "There are not four free earth beads, so use friends of five: drop the heaven bead (5) and take away 4's friend, 1 - leaving 7." },
      },
      {
        type: "quiz",
        prompt: "4 + 4 + 4 = ?",
        choices: [12, 10, 14, 11],
        answer: 12,
        explanation: { text: "4 + 4 is 8, and one more 4 makes 12 - your running board settles on 12." },
      },
      {
        type: "quiz",
        prompt: "2 + 3 + 4 = ?",
        choices: [9, 8, 10, 7],
        answer: 9,
        explanation: { text: "2 + 3 is 5, then add 4 more to land on 9." },
      },
    ],
    "carry-in-your-head": [
      { type: "heading", text: "Carry in your head" },
      {
        type: "paragraph",
        text: "Eight plus five cannot fit on one rod — even in your imagination. Picture the ones rod overflowing, then carry: clear the rod down and add one bead to the tens rod. The board shows 13.",
      },
      {
        type: "paragraph",
        text: "Think of it as trading ten ones for one ten, exactly as you would on a real soroban.",
      },
      {
        type: "quiz",
        prompt: "8 + 5 = ?",
        choices: [13, 12, 15, 11],
        answer: 13,
        explanation: { text: "8 needs 2 more to fill the ones rod, so you carry one ten and leave 3 - the answer is 13." },
      },
      {
        type: "quiz",
        prompt: "9 + 9 = ?",
        choices: [18, 17, 19, 16],
        answer: 18,
        explanation: { text: "Each 9 needs just 1 more to carry a ten, so 9 + 9 fills the ones rod and leaves 1 ten and 8 ones - 18." },
      },
      {
        type: "quiz",
        prompt: "7 + 8 = ?",
        choices: [15, 14, 16, 13],
        answer: 15,
        explanation: { text: "7 needs 3 to fill the ones rod, so 8 carries one ten and leaves 5 ones - the board shows 15." },
      },
      {
        type: "build",
        prompt: "Show 8 + 5 = 13 on the abacus to confirm your mental carry.",
        target: 13,
        rods: 2,
        explanation: { text: "8 + 5 really is 13, so build 1 ten and 3 ones to confirm the carry you just did in your head." },
      },
    ],
    "two-digit-mental-add": [
      { type: "heading", text: "Two-digit addition in your head" },
      {
        type: "paragraph",
        text: "Add two-digit numbers rod by rod, exactly like written arithmetic — but the beads do the place-keeping. Picture 27: two earth beads on the tens rod, heaven plus two earths on the ones rod. Now add 15: one more ten, then five ones that carry the board to 42.",
      },
      {
        type: "quiz",
        prompt: "27 + 15 = ?",
        choices: [42, 32, 52, 43],
        answer: 42,
        explanation: { text: "Tens first: 2 + 1 is 3 tens. Ones: 7 + 5 is 12, which carries to 4 tens and leaves 2 ones - 42." },
      },
      {
        type: "quiz",
        prompt: "34 + 26 = ?",
        choices: [60, 50, 70, 56],
        answer: 60,
        explanation: { text: "3 tens + 2 tens is 5 tens. Ones: 4 + 6 is 10, which carries to 6 tens and 0 ones - 60." },
      },
      {
        type: "quiz",
        prompt: "58 + 27 = ?",
        choices: [85, 75, 95, 84],
        answer: 85,
        explanation: { text: "5 tens + 2 tens is 7 tens. Ones: 8 + 7 is 15, which carries to 8 tens and leaves 5 ones - 85." },
      },
      {
        type: "build",
        prompt: "Show 58 + 27 = 85 to verify your mental carries.",
        target: 85,
        rods: 2,
        explanation: { text: "58 + 27 really is 85, so build 8 tens and 5 ones to verify your carrying." },
      },
    ],
    "mental-add-string": [
      { type: "heading", text: "Add a few in a row" },
      {
        type: "paragraph",
        text: "Anzan is built on strings: a series of numbers added one after another to a running total. Start with three small numbers, keep the running total on your mental board, and never go back to restart.",
      },
      {
        type: "quiz",
        prompt: "3 + 6 + 4 = ?",
        choices: [13, 12, 14, 11],
        answer: 13,
        explanation: { text: "Keep one running total: 3 + 6 is 9, then +4 is 13." },
      },
      {
        type: "quiz",
        prompt: "8 + 5 + 7 = ?",
        choices: [20, 19, 21, 18],
        answer: 20,
        explanation: { text: "8 + 5 is 13 (carry a ten), then +7 brings the running total to 20." },
      },
      {
        type: "quiz",
        prompt: "12 + 9 + 14 = ?",
        choices: [35, 33, 36, 34],
        answer: 35,
        explanation: { text: "12 + 9 is 21, then +14 gives 35 - just keep adding to the total." },
      },
    ],
    "mental-addition-check": [
      { type: "heading", text: "Level check — mental addition" },
      { type: "paragraph", text: "Keep the running total on your mental board. Solve every question to finish." },
      {
        type: "quiz",
        prompt: "5 + 6 = ?",
        choices: [11, 10, 12, 13],
        answer: 11,
        explanation: { text: "5 needs 5 to fill, and 6 gives it 5 plus 1 - the ones rod carries and you see 11 (1 ten and 1 one)." },
      },
      {
        type: "quiz",
        prompt: "27 + 19 = ?",
        choices: [46, 44, 45, 47],
        answer: 46,
        explanation: { text: "2 tens + 1 ten is 3 tens. Ones: 7 + 9 is 16, which carries to 4 tens and leaves 6 ones - 46." },
      },
      {
        type: "quiz",
        prompt: "4 + 7 + 8 + 6 = ?",
        choices: [25, 24, 26, 23],
        answer: 25,
        explanation: { text: "Run a single total: 4 + 7 is 11, +8 is 19, +6 is 25." },
      },
      {
        type: "build",
        prompt: "Show the answer to 8 + 9 = 17 on the beads.",
        target: 17,
        rods: 2,
        explanation: { text: "8 + 9 really is 17, so build 1 ten and 7 ones on the board." },
      },
    ],
  },

  "mental-subtraction": {
    "subtract-without-trading": [
      { type: "heading", text: "Subtract without trading" },
      {
        type: "paragraph",
        text: "Subtraction on your mental board is addition in reverse: slide earth beads away from the beam. Picture 9, remove 3, and the rod shows 6.",
      },
      {
        type: "quiz",
        prompt: "9 − 3 = ?",
        choices: [6, 5, 7, 8],
        answer: 6,
        explanation: { text: "Take three earth beads away from the 9 on your rod, and 6 stay touching the beam." },
      },
      {
        type: "quiz",
        prompt: "7 − 2 = ?",
        choices: [5, 4, 6, 3],
        answer: 5,
        explanation: { text: "With 7 on the rod, slide two earth beads away and the heaven bead alone is left - 5." },
      },
      {
        type: "build",
        prompt: "Show 9 − 3 = 6 on the rod.",
        target: 6,
        rods: 1,
        explanation: { text: "9 - 3 is 6, so rebuild the rod with one heaven bead (5) and one earth bead (1)." },
      },
    ],
    "break-five": [
      { type: "heading", text: "Break five mentally" },
      {
        type: "paragraph",
        text: "What if the bead you must remove isn't there? To take 3 away from 6, you cannot remove three earth beads — only one is up. So you break the five: take the heaven bead off (−5) and add back three's friend of five (+2). Six loses five and gains two: 3.",
      },
      {
        type: "paragraph",
        text: "Read it as beads: heaven bead off, two earth beads up. The board shows 3.",
      },
      {
        type: "quiz",
        prompt: "6 − 3 = ?",
        choices: [3, 2, 4, 5],
        answer: 3,
        explanation: { text: "You cannot take 3 earth beads straight off a 6, so break the five: drop the heaven bead (-5) and add back 3's friend of five (+2) - leaving 3." },
      },
      {
        type: "quiz",
        prompt: "8 − 4 = ?",
        choices: [4, 3, 5, 6],
        answer: 4,
        explanation: { text: "8 is heaven plus three earths, so to remove 4 you break the five: take off the 5 and add back 4's friend of five (1) - leaving 4." },
      },
      {
        type: "build",
        prompt: "Show 7 − 2 = 5. Which bead do you break?",
        target: 5,
        rods: 1,
        explanation: { text: "7 - 2 is 5, so from the 7 (heaven plus two earths) take two earth beads away and only the heaven bead is left - no break is needed." },
      },
    ],
    "borrow-in-your-head": [
      { type: "heading", text: "Borrow in your head" },
      {
        type: "paragraph",
        text: "When a rod cannot lose enough ones, borrow one ten from the rod to its left and add back the difference on the short rod. For 13 − 5: the tens rod loses one, and the ones rod gains 10 − 5 = 5 on top of its 3 → 8.",
      },
      {
        type: "paragraph",
        text: "Borrowing is the mirror of carrying — the same trade, in reverse.",
      },
      {
        type: "quiz",
        prompt: "13 − 5 = ?",
        choices: [8, 7, 9, 6],
        answer: 8,
        explanation: { text: "Borrow a ten so the ones rod holds 10 + 3 = 13, then subtract 5 to leave 8." },
      },
      {
        type: "quiz",
        prompt: "12 − 7 = ?",
        choices: [5, 6, 4, 7],
        answer: 5,
        explanation: { text: "Borrow a ten so the ones become 10 + 2 = 12, then 12 - 7 leaves 5 in the ones." },
      },
      {
        type: "quiz",
        prompt: "20 − 6 = ?",
        choices: [14, 13, 15, 12],
        answer: 14,
        explanation: { text: "Borrow a ten off the 20 so the ones rod gets 10; 10 - 6 is 4, and one ten remains - 14." },
      },
      {
        type: "build",
        prompt: "Show 13 − 5 = 8 on the abacus.",
        target: 8,
        rods: 2,
        explanation: { text: "13 - 5 is 8, so build 8 on the ones rod (a heaven bead and three earths) and leave the tens rod empty." },
      },
    ],
    "two-digit-mental-sub": [
      { type: "heading", text: "Two-digit subtraction in your head" },
      {
        type: "paragraph",
        text: "Line up the rods and subtract place by place, borrowing whenever a rod comes up short. Picture 52 and subtract 28: the ones cannot lose eight, so you borrow, and the tens rod drops by one as the ones rod gains two.",
      },
      {
        type: "quiz",
        prompt: "52 − 28 = ?",
        choices: [24, 34, 26, 14],
        answer: 24,
        explanation: { text: "Borrow a ten so the ones become 12; 12 - 8 is 4, and the tens go 4 - 2 after the borrow - 24." },
      },
      {
        type: "quiz",
        prompt: "81 − 36 = ?",
        choices: [45, 55, 35, 46],
        answer: 45,
        explanation: { text: "Borrow a ten so the ones become 11; 11 - 6 is 5, and the tens go 7 - 3 - 45." },
      },
      {
        type: "quiz",
        prompt: "64 − 27 = ?",
        choices: [37, 47, 36, 27],
        answer: 37,
        explanation: { text: "Borrow a ten so the ones become 14; 14 - 7 is 7, and the tens go 5 - 2 - 37." },
      },
      {
        type: "build",
        prompt: "Show 81 − 36 = 45 on the abacus.",
        target: 45,
        rods: 2,
        explanation: { text: "81 - 36 is 45, so build 4 tens and 5 ones on the board." },
      },
    ],
    "mental-subtraction-check": [
      { type: "heading", text: "Level check — mental subtraction" },
      { type: "paragraph", text: "Break, borrow, and subtract your way to the finish." },
      {
        type: "quiz",
        prompt: "15 − 8 = ?",
        choices: [7, 6, 8, 9],
        answer: 7,
        explanation: { text: "Borrow a ten so the ones become 15, then 15 - 8 leaves 7." },
      },
      {
        type: "quiz",
        prompt: "70 − 25 = ?",
        choices: [45, 55, 35, 44],
        answer: 45,
        explanation: { text: "Borrow a ten so the ones become 10; 10 - 5 is 5, and the tens go 6 - 2 - 45." },
      },
      {
        type: "quiz",
        prompt: "11 − 4 − 3 = ?",
        choices: [4, 5, 6, 3],
        answer: 4,
        explanation: { text: "Take it in two steps: 11 - 4 is 7, then subtract 3 more to get 4." },
      },
      {
        type: "build",
        prompt: "Show 62 − 27 = 35 on the abacus.",
        target: 35,
        rods: 2,
        explanation: { text: "62 - 27 is 35, so build 3 tens and 5 ones." },
      },
    ],
  },

  "strings-and-speed": {
    "running-totals": [
      { type: "heading", text: "Keep a running total" },
      {
        type: "paragraph",
        text: "The heart of flash anzan is adding a long list to one running total. Start with three or four two-digit numbers. After each number you update the total on your mental board; you never start over.",
      },
      {
        type: "quiz",
        prompt: "Start at 0. Add 15, then 20, then 5. What is the total?",
        choices: [40, 35, 45, 30],
        answer: 40,
        explanation: { text: "Run the total: 0 + 15 is 15, +20 is 35, +5 is 40." },
      },
      {
        type: "quiz",
        prompt: "25 + 30 + 12 + 8 = ?",
        choices: [75, 65, 85, 74],
        answer: 75,
        explanation: { text: "Keep going: 25 + 30 is 55, +12 is 67, +8 is 75." },
      },
      {
        type: "quiz",
        prompt: "Start at 40, add 16, then 24. Total?",
        choices: [80, 70, 90, 76],
        answer: 80,
        explanation: { text: "40 + 16 is 56, then +24 brings the total to 80." },
      },
    ],
    "spot-the-carry": [
      { type: "heading", text: "See a carry before it happens" },
      {
        type: "paragraph",
        text: "The fastest students don't wait for a rod to overflow — they see it coming. When your ones rod shows 7, it needs 3 more to fill, so adding 5 or more will always carry.",
      },
      {
        type: "paragraph",
        text: "Predict before you slide: '27's ones rod needs 3 to fill; adding 6 carries one to the tens.' Then run it — the board settles on 33.",
      },
      {
        type: "quiz",
        prompt: "38 + 7 = ?",
        choices: [45, 44, 46, 43],
        answer: 45,
        explanation: { text: "38's ones rod needs 2 to fill, so 7 carries: 38 + 2 is 40, then +5 more is 45." },
      },
      {
        type: "quiz",
        prompt: "46 + 8 = ?",
        choices: [54, 53, 55, 52],
        answer: 54,
        explanation: { text: "46 needs 4 to fill, so 8 carries: 46 + 4 is 50, then +4 more is 54." },
      },
      {
        type: "quiz",
        prompt: "75 + 9 = ?",
        choices: [84, 83, 85, 82],
        answer: 84,
        explanation: { text: "75 needs 5 to fill, so 9 carries: 75 + 5 is 80, then +4 more is 84." },
      },
    ],
    "two-rods-at-once": [
      { type: "heading", text: "Two rods at once" },
      {
        type: "paragraph",
        text: "Longer numbers are easier when you see tens and ones together. For 34 + 21, picture 3 tens with 4 ones meeting 2 tens with 1 one, merging into 5 tens and 5 ones — 55.",
      },
      {
        type: "quiz",
        prompt: "34 + 21 = ?",
        choices: [55, 65, 54, 45],
        answer: 55,
        explanation: { text: "3 tens + 2 tens is 5 tens, and 4 ones + 1 one is 5 - so 55." },
      },
      {
        type: "quiz",
        prompt: "26 + 43 = ?",
        choices: [69, 79, 68, 59],
        answer: 69,
        explanation: { text: "2 tens + 4 tens is 6 tens, and 6 ones + 3 ones is 9 - so 69." },
      },
      {
        type: "quiz",
        prompt: "51 + 38 = ?",
        choices: [89, 99, 88, 79],
        answer: 89,
        explanation: { text: "5 tens + 3 tens is 8 tens, and 1 one + 8 ones is 9 - so 89." },
      },
      {
        type: "build",
        prompt: "Show 51 + 38 = 89 on the abacus.",
        target: 89,
        rods: 2,
        explanation: { text: "51 + 38 is 89, so build 8 tens and 9 ones." },
      },
    ],
    "flash-anzan": [
      { type: "heading", text: "Flash anzan" },
      {
        type: "paragraph",
        text: "Flash anzan is the showpiece: numbers appear one after another, and you add each one to your mental board before the next flashes. Champions add ten or more numbers shown for under a second each.",
      },
      {
        type: "paragraph",
        text: "This app can't flash numbers at you yet, so build the skill with a friend or flashcards: have someone read a list aloud at a steady beat while you keep the total on your mental board.",
      },
      {
        type: "list",
        items: [
          "Start with three numbers, each held for a full second.",
          "Add each one to the running total — never clear between numbers.",
          "When you can do five without losing the picture, go faster.",
        ],
      },
      {
        type: "quiz",
        prompt: "A quick warm-up string: 14, then 23, then 12. Total?",
        choices: [49, 48, 50, 47],
        answer: 49,
        explanation: { text: "14 + 23 is 37, then +12 is 49 - add each flashed number to the running total." },
      },
      {
        type: "quiz",
        prompt: "Now a longer string: 31, 25, 44. Total?",
        choices: [100, 99, 101, 110],
        answer: 100,
        explanation: { text: "31 + 25 is 56, then +44 is 100 - the total rolls over into a full hundred." },
      },
    ],
    "strings-speed-check": [
      { type: "heading", text: "Level check — strings and speed" },
      { type: "paragraph", text: "Keep one running total for each string and finish the level." },
      {
        type: "quiz",
        prompt: "12 + 15 + 8 = ?",
        choices: [35, 33, 36, 34],
        answer: 35,
        explanation: { text: "12 + 15 is 27, then +8 is 35." },
      },
      {
        type: "quiz",
        prompt: "30 + 22 + 18 = ?",
        choices: [70, 60, 72, 68],
        answer: 70,
        explanation: { text: "30 + 22 is 52, then +18 is 70." },
      },
      {
        type: "quiz",
        prompt: "46 + 17 + 9 = ?",
        choices: [72, 71, 73, 62],
        answer: 72,
        explanation: { text: "46 + 17 is 63, then +9 is 72." },
      },
      {
        type: "build",
        prompt: "Show the string 31 + 25 + 44 = 100 on the abacus.",
        target: 100,
        rods: 3,
        explanation: { text: "31 + 25 + 44 really is 100, so build 1 on the hundreds rod and leave the tens and ones rods empty." },
      },
    ],
  },

  "big-numbers": {
    "three-digit-add": [
      { type: "heading", text: "Three-digit mental addition" },
      {
        type: "paragraph",
        text: "Your mental board grows a third rod. Anchor hundreds on the left, tens in the middle, ones on the right, and add place by place from the right, carrying leftward whenever a rod overflows.",
      },
      {
        type: "quiz",
        prompt: "123 + 456 = ?",
        choices: [579, 569, 589, 578],
        answer: 579,
        explanation: { text: "Place by place: hundreds 1 + 4 is 5, tens 2 + 5 is 7, ones 3 + 6 is 9 - 579." },
      },
      {
        type: "quiz",
        prompt: "456 + 789 = ?",
        choices: [1245, 1244, 1135, 1255],
        answer: 1245,
        explanation: { text: "Ones: 6 + 9 is 15 (write 5, carry 1). Tens: 5 + 8 + 1 is 14 (write 4, carry 1). Hundreds: 4 + 7 + 1 is 12, giving 1245." },
      },
      {
        type: "quiz",
        prompt: "345 + 278 = ?",
        choices: [623, 613, 633, 622],
        answer: 623,
        explanation: { text: "Ones: 5 + 8 is 13 (carry 1). Tens: 4 + 7 + 1 is 12 (carry 1). Hundreds: 3 + 2 + 1 is 6 - 623." },
      },
      {
        type: "build",
        prompt: "Show 345 + 278 = 623 on the abacus.",
        target: 623,
        rods: 3,
        explanation: { text: "345 + 278 really is 623, so build 6 hundreds, 2 tens, and 3 ones." },
      },
    ],
    "three-digit-sub": [
      { type: "heading", text: "Three-digit mental subtraction" },
      {
        type: "paragraph",
        text: "Subtraction across hundreds is the same routine one rod higher: take away place by place and borrow from the next rod when a place comes up short.",
      },
      {
        type: "quiz",
        prompt: "652 − 231 = ?",
        choices: [421, 431, 411, 321],
        answer: 421,
        explanation: { text: "Place by place: hundreds 6 - 2 is 4, tens 5 - 3 is 2, ones 2 - 1 is 1 - 421." },
      },
      {
        type: "quiz",
        prompt: "800 − 356 = ?",
        choices: [444, 454, 434, 544],
        answer: 444,
        explanation: { text: "800 has no ones and no tens, so borrow across: ones 10 - 6 is 4, tens 9 - 5 is 4, hundreds 7 - 3 is 4 - 444." },
      },
      {
        type: "quiz",
        prompt: "923 − 468 = ?",
        choices: [455, 465, 445, 555],
        answer: 455,
        explanation: { text: "Borrow for the ones: 13 - 8 is 5. Tens: borrow so 11 - 6 is 5. Hundreds: 8 - 4 is 4 - 455." },
      },
      {
        type: "build",
        prompt: "Show 800 − 356 = 444 on the abacus.",
        target: 444,
        rods: 3,
        explanation: { text: "800 - 356 really is 444, so build 4 hundreds, 4 tens, and 4 ones." },
      },
    ],
    "decimals-money": [
      { type: "heading", text: "Decimals and money" },
      {
        type: "paragraph",
        text: "Money is where mental abacus shines in daily life. Fix an imaginary decimal point as a place on your board and treat cents as ones: $4.50 + $2.25 becomes 450 + 225 = 675, which you read back as $6.75.",
      },
      {
        type: "paragraph",
        text: "The decimal point is imaginary — like the board itself. Just remember which rod is your ones rod.",
      },
      {
        type: "quiz",
        prompt: "$4.50 + $2.25 = ?",
        choices: [6.75, 6.25, 7.75, 5.75],
        answer: 6.75,
        explanation: { text: "Treat the money as cents: 450 + 225 is 675, which you read back as $6.75." },
      },
      {
        type: "quiz",
        prompt: "$1.99 + $2.01 = ?",
        choices: [4, 4.5, 3.99, 3.9],
        answer: 4,
        explanation: { text: "0.99 and 0.01 make one whole dollar, so $1.99 + $2.01 is exactly $4.00." },
      },
      {
        type: "quiz",
        prompt: "0.70 + 0.80 = ?",
        choices: [1.5, 1.4, 0.15, 1.05],
        answer: 1.5,
        explanation: { text: "7 tenths plus 8 tenths is 15 tenths - which carries to 1 whole and 5 tenths, or 1.5." },
      },
    ],
    "mixed-operations": [
      { type: "heading", text: "Mixed-up math" },
      {
        type: "paragraph",
        text: "Strings don't have to be all addition. The rule is the same: one running total, updated with each next term. Start at zero and perform each step on the beads.",
      },
      {
        type: "quiz",
        prompt: "20 + 15 − 8 = ?",
        choices: [27, 25, 28, 26],
        answer: 27,
        explanation: { text: "Keep one running total: 20 + 15 is 35, then -8 is 27." },
      },
      {
        type: "quiz",
        prompt: "50 − 12 + 7 = ?",
        choices: [45, 44, 46, 55],
        answer: 45,
        explanation: { text: "50 - 12 is 38, then +7 is 45." },
      },
      {
        type: "quiz",
        prompt: "100 − 35 − 18 = ?",
        choices: [47, 48, 46, 57],
        answer: 47,
        explanation: { text: "100 - 35 is 65, then -18 is 47." },
      },
      {
        type: "build",
        prompt: "Show 50 − 12 + 7 = 45 on the abacus.",
        target: 45,
        rods: 2,
        explanation: { text: "50 - 12 + 7 really is 45, so build 4 tens and 5 ones." },
      },
    ],
    "big-numbers-check": [
      { type: "heading", text: "Level check — big boards and mixed numbers" },
      { type: "paragraph", text: "Add, subtract, and keep your place — even with a decimal point." },
      {
        type: "quiz",
        prompt: "268 + 174 = ?",
        choices: [442, 432, 452, 342],
        answer: 442,
        explanation: { text: "Ones: 8 + 4 is 12 (carry 1). Tens: 6 + 7 + 1 is 14 (carry 1). Hundreds: 2 + 1 + 1 is 4 - 442." },
      },
      {
        type: "quiz",
        prompt: "900 − 268 = ?",
        choices: [632, 642, 622, 732],
        answer: 632,
        explanation: { text: "Borrow across: ones 10 - 8 is 2, tens 9 - 6 is 3, hundreds 8 - 2 is 6 - 632." },
      },
      {
        type: "quiz",
        prompt: "$3.50 + $2.75 = ?",
        choices: [6.25, 6.75, 6.5, 5.75],
        answer: 6.25,
        explanation: { text: "As cents: 350 + 275 is 625, which you read back as $6.25." },
      },
      {
        type: "build",
        prompt: "Show 268 + 174 = 442 on the abacus.",
        target: 442,
        rods: 3,
        explanation: { text: "268 + 174 really is 442, so build 4 hundreds, 4 tens, and 2 ones." },
      },
    ],
  },

  "anzan-mastery": {
    "speed-habits": [
      { type: "heading", text: "Speed-training habits" },
      {
        type: "paragraph",
        text: "Speed is built in short, focused sessions. Five minutes daily beats an hour on Sunday. Start every session by clearing your mental board and doing one slow, clean run — then time the next.",
      },
      {
        type: "list",
        items: [
          "Warm up by reading and building numbers slowly.",
          "Repeat the same string until it is clean, then go faster.",
          "Stop when your picture blurs — rest beats sloppy reps.",
        ],
      },
      {
        type: "quiz",
        prompt: "Warm-up check: 18 + 25 = ?",
        choices: [43, 42, 44, 53],
        answer: 43,
        explanation: { text: "Ones: 8 + 5 is 13 (carry 1). Tens: 1 + 2 + 1 is 4 - 43." },
      },
    ],
    "stronger-images": [
      { type: "heading", text: "Make your mental image vivid" },
      {
        type: "paragraph",
        text: "Vividness is trainable. Always picture the same board: dark frame, amber beam, red heaven bead, blue earth beads. When your image fades, go back to the real board for a minute and re-fire the photograph.",
      },
      {
        type: "paragraph",
        text: "Practise 'drawing' the board with your eyes closed after you clear it — from 0 beads up to a full board and back down.",
      },
      {
        type: "quiz",
        prompt: "Refresh drill: 4 + 9 = ?",
        choices: [13, 12, 14, 15],
        answer: 13,
        explanation: { text: "9 needs 1 more to fill the ones rod, so it carries - 4 + 9 leaves 1 ten and 3 ones, or 13." },
      },
      {
        type: "quiz",
        prompt: "Hold 56 in mind, then subtract 19. What do you see?",
        choices: [37, 36, 38, 47],
        answer: 37,
        explanation: { text: "Borrow a ten so the ones become 16; 16 - 9 is 7, and the tens go 4 - 1 - 37." },
      },
    ],
    "ten-number-sprint": [
      { type: "heading", text: "The ten-number sprint" },
      {
        type: "paragraph",
        text: "The classic anzan drill: add ten numbers to one running total. Have someone read a list aloud while you keep the total on your mental board — then say the final number out loud.",
      },
      {
        type: "paragraph",
        text: "Try this list now, adding each number to your mental board as you go: 6, 14, 9, 21, 7, 13, 18, 5, 22, 10.",
      },
      {
        type: "quiz",
        prompt: "What is the running total after that whole sprint list?",
        choices: [125, 120, 118, 132],
        answer: 125,
        explanation: { text: "Add the whole sprint 6 + 14 + 9 + 21 + 7 + 13 + 18 + 5 + 22 + 10 to one running total and it lands on 125." },
      },
      {
        type: "quiz",
        prompt: "Shorter sprint: 12 + 8 + 15 + 5 + 20 = ?",
        choices: [60, 55, 62, 58],
        answer: 60,
        explanation: { text: "12 + 8 is 20, +15 is 35, +5 is 40, +20 is 60." },
      },
    ],
    "anzan-mastery-check": [
      { type: "heading", text: "Final challenge" },
      { type: "paragraph", text: "A mini championship set. Keep your mental board steady and solve every question." },
      {
        type: "quiz",
        prompt: "34 + 27 = ?",
        choices: [61, 60, 62, 51],
        answer: 61,
        explanation: { text: "Ones: 4 + 7 is 11 (carry 1). Tens: 3 + 2 + 1 is 6 - 61." },
      },
      {
        type: "quiz",
        prompt: "100 − 47 + 12 = ?",
        choices: [65, 64, 66, 55],
        answer: 65,
        explanation: { text: "100 - 47 is 53, then +12 is 65." },
      },
      {
        type: "quiz",
        prompt: "A string: 5 + 18 + 24 + 6 = ?",
        choices: [53, 52, 54, 43],
        answer: 53,
        explanation: { text: "5 + 18 is 23, +24 is 47, +6 is 53." },
      },
      {
        type: "quiz",
        prompt: "$12.40 + $8.60 = ?",
        choices: [21, 20.4, 21.4, 20],
        answer: 21,
        explanation: { text: "As cents: 1240 + 860 is 2100, which you read back as $21.00." },
      },
      {
        type: "build",
        prompt: "Show the final sprint result: 6 + 14 + 9 + 21 + 7 + 13 + 18 + 5 + 22 + 10 = 125.",
        target: 125,
        rods: 3,
        explanation: { text: "The sprint 6 + 14 + 9 + 21 + 7 + 13 + 18 + 5 + 22 + 10 really totals 125, so build 1 hundred, 2 tens, and 5 ones." },
      },
    ],
  },
};
