import { understandingAbacusCourse } from "./understanding-abacus";
import { anzanCourse } from "./anzan";
import { zhuxinsuanCourse } from "./zhuxinsuan";
import { chineseNumbersCourse } from "./chinese-numbers";
import type { Course, CourseSummary } from "./types";

export const courseCatalog: CourseSummary[] = [
  {
    slug: understandingAbacusCourse.slug,
    title: understandingAbacusCourse.title,
    tagline: understandingAbacusCourse.tagline,
    description: understandingAbacusCourse.description,
    subject: "Abacus",
    levelCount: understandingAbacusCourse.levels.length,
    lessonCount: understandingAbacusCourse.lessonCount,
    exerciseCount: understandingAbacusCourse.exerciseCount,
    lessonMinutes: understandingAbacusCourse.lessonMinutes,
    accent: understandingAbacusCourse.accent,
    heroAccent: understandingAbacusCourse.heroAccent,
    status: "available",
    sample: [4, 3, 2, 1],
    art: "bead",
  },
  {
    slug: anzanCourse.slug,
    title: anzanCourse.title,
    tagline: anzanCourse.tagline,
    description: anzanCourse.description,
    subject: "Abacus",
    levelCount: anzanCourse.levels.length,
    lessonCount: anzanCourse.lessonCount,
    exerciseCount: anzanCourse.exerciseCount,
    lessonMinutes: anzanCourse.lessonMinutes,
    accent: anzanCourse.accent,
    heroAccent: anzanCourse.heroAccent,
    status: "available",
    sample: anzanCourse.sample ?? [0, 7, 5, 2],
    art: "mental",
  },
  {
    slug: zhuxinsuanCourse.slug,
    title: zhuxinsuanCourse.title,
    tagline: zhuxinsuanCourse.tagline,
    description: zhuxinsuanCourse.description,
    subject: "Abacus",
    levelCount: zhuxinsuanCourse.levels.length,
    lessonCount: zhuxinsuanCourse.lessonCount,
    exerciseCount: zhuxinsuanCourse.exerciseCount,
    lessonMinutes: zhuxinsuanCourse.lessonMinutes,
    accent: zhuxinsuanCourse.accent,
    heroAccent: zhuxinsuanCourse.heroAccent,
    status: "available",
    sample: zhuxinsuanCourse.sample ?? [6, 1, 4, 2],
    art: "suanpan",
  },
  {
    slug: chineseNumbersCourse.slug,
    title: chineseNumbersCourse.title,
    tagline: chineseNumbersCourse.tagline,
    description: chineseNumbersCourse.description,
    subject: "Abacus",
    levelCount: chineseNumbersCourse.levels.length,
    lessonCount: chineseNumbersCourse.lessonCount,
    exerciseCount: chineseNumbersCourse.exerciseCount,
    lessonMinutes: chineseNumbersCourse.lessonMinutes,
    accent: chineseNumbersCourse.accent,
    heroAccent: chineseNumbersCourse.heroAccent,
    status: "available",
    sample: chineseNumbersCourse.sample ?? [4, 3, 2, 1],
    art: "numerals",
  },
  {
    slug: "math-fundamentals",
    title: "Math Fundamentals",
    tagline: "Fractions, ratios & number sense.",
    description: "Build an intuition for fractions and core number skills with visual, hands-on lessons.",
    subject: "Math",
    levelCount: 5,
    lessonCount: 27,
    exerciseCount: 240,
    lessonMinutes: 110,
    accent: "bg-gradient-to-br from-sky-100 to-indigo-100",
    heroAccent: "from-sky-400 via-blue-300 to-indigo-200",
    status: "coming-soon",
    sample: [6, 3, 5, 2],
  },
  {
    slug: "solving-equations",
    title: "Solving Equations",
    tagline: "Make variables behave.",
    description: "Meet algebra the visual way: balance, undo, and solve equations with confidence.",
    subject: "Math",
    levelCount: 4,
    lessonCount: 24,
    exerciseCount: 200,
    lessonMinutes: 100,
    accent: "bg-gradient-to-br from-fuchsia-100 to-pink-100",
    heroAccent: "from-fuchsia-400 via-pink-300 to-rose-200",
    status: "coming-soon",
    sample: [0, 9, 4, 3],
  },
  {
    slug: "abacus-addition",
    title: "Addition in Action",
    tagline: "Speed up sums of any size.",
    description: "Practice the finger moves of abacus addition until sums feel instant.",
    subject: "Abacus",
    levelCount: 4,
    lessonCount: 18,
    exerciseCount: 120,
    lessonMinutes: 70,
    accent: "bg-gradient-to-br from-rose-100 to-red-100",
    heroAccent: "from-rose-400 via-red-300 to-orange-200",
    status: "coming-soon",
    sample: [8, 2, 6, 3],
  },
  {
    slug: "scientific-thinking",
    title: "Scientific Thinking",
    tagline: "Reason like a scientist.",
    description: "Design experiments, hunt for bias, and argue from evidence — the scientist's toolkit.",
    subject: "Science",
    levelCount: 4,
    lessonCount: 21,
    exerciseCount: 180,
    lessonMinutes: 95,
    accent: "bg-gradient-to-br from-emerald-100 to-teal-100",
    heroAccent: "from-emerald-400 via-teal-300 to-cyan-200",
    status: "coming-soon",
    sample: [6, 4, 1, 5],
  },
  {
    slug: "think-like-a-programmer",
    title: "Think Like a Programmer",
    tagline: "Logic first, code later.",
    description: "Solve puzzles that teach the core ideas behind every programming language.",
    subject: "Coding",
    levelCount: 4,
    lessonCount: 20,
    exerciseCount: 150,
    lessonMinutes: 85,
    accent: "bg-gradient-to-br from-lime-100 to-emerald-100",
    heroAccent: "from-lime-400 via-green-300 to-emerald-200",
    status: "coming-soon",
    sample: [9, 1, 7, 2],
  },
  {
    slug: "daily-challenges",
    title: "Daily Challenges",
    tagline: "A puzzle for every day.",
    description: "Fresh bite-size problems across every subject to keep your mind sharp.",
    subject: "Mixed",
    levelCount: 1,
    lessonCount: 365,
    exerciseCount: 500,
    lessonMinutes: 30,
    accent: "bg-gradient-to-br from-amber-100 to-yellow-100",
    heroAccent: "from-amber-400 via-yellow-300 to-lime-200",
    status: "coming-soon",
    sample: [3, 8, 0, 6],
  },
  {
    slug: "fractions",
    title: "Fractions",
    tagline: "Halves, thirds, and the spaces between.",
    description:
      "See why fractions behave the way they do — split, compare, and combine parts of a whole.",
    subject: "Math",
    levelCount: 4,
    lessonCount: 22,
    exerciseCount: 180,
    lessonMinutes: 95,
    accent: "bg-gradient-to-br from-sky-100 to-indigo-100",
    heroAccent: "from-sky-400 via-blue-300 to-indigo-200",
    status: "coming-soon",
    sample: [6, 3, 5, 2],
    art: "fractions",
  },
];

export function getCourseBySlug(slug: string): Course | undefined {
  if (slug === understandingAbacusCourse.slug) {
    return understandingAbacusCourse;
  }
  if (slug === anzanCourse.slug) {
    return anzanCourse;
  }
  if (slug === zhuxinsuanCourse.slug) {
    return zhuxinsuanCourse;
  }
  if (slug === chineseNumbersCourse.slug) {
    return chineseNumbersCourse;
  }
  return undefined;
}
