const mockCourse = {
  __typename: "Course",
  id: "ZokqoDVlDocAriapm",
  description:
    "In this course, we'll build your understanding of fractions using visuals. You'll improve your intuition for fractions and fluency working with them.",
  imageUrl:
    "https://ds055uzetaobb.cloudfront.net/brioche/chapter/Arithmetic_Thinking-KaQBTB.png",
  title: "Fractions",
  slug: "math-fundamentals",
  versionName: "V60",
  versionStateName: "Default",
  gameboardV2: {
    __typename: "Gameboard",
    levels: [
      {
        __typename: "GameboardLevel",
        slug: "mt-fractions-intro",
        contentAccessStatus: "AVAILABLE",
        name: "Visualize Fractions",
        descriptionBullet1: "Visualize fractions of a shape.",
        descriptionBullet2: null,
        nodesV2: [
          {
            __typename: "GameboardLessonNode",
            lessonSlug: "find-half",
            nodeKey: "find-half",
            title: "Finding Half",
            contentUrl:
              "/courses/math-fundamentals/mt-fractions-intro/find-half/",
            hasOverviewVideo: false,
            isMeterLocked: false,
            isPremiumLocked: false,
            lessonNodeAction: "START",
            lessonNodeStatus: "NOT_STARTED",
            lessonVersionName: null,
            nextPracticeSlug: "find-half-set1",
            gatingLevelCheck: null,
          },
          {
            __typename: "GameboardLessonNode",
            lessonSlug: "combining-parts",
            nodeKey: "combining-parts",
            title: "Combining Parts",
            contentUrl:
              "/courses/math-fundamentals/mt-fractions-intro/combining-parts/",
            hasOverviewVideo: false,
            isMeterLocked: false,
            isPremiumLocked: false,
            lessonNodeAction: "JUMP_AHEAD_LOCKED",
            lessonNodeStatus: "NOT_STARTED",
            lessonVersionName: null,
            nextPracticeSlug: "combining-parts-1",
            gatingLevelCheck: null,
          },
          {
            __typename: "GameboardLessonNode",
            lessonSlug: "take-more-than-one",
            nodeKey: "take-more-than-one",
            title: "Splitting Parts",
            contentUrl:
              "/courses/math-fundamentals/mt-fractions-intro/take-more-than-one/",
            hasOverviewVideo: false,
            isMeterLocked: false,
            isPremiumLocked: false,
            lessonNodeAction: "JUMP_AHEAD_LOCKED",
            lessonNodeStatus: "NOT_STARTED",
            lessonVersionName: null,
            nextPracticeSlug: "splitting-parts-1",
            gatingLevelCheck: null,
          },
          {
            __typename: "GameboardLessonNode",
            lessonSlug: "shade-this-much",
            nodeKey: "shade-this-much",
            title: "Splitting and Combining",
            contentUrl:
              "/courses/math-fundamentals/mt-fractions-intro/shade-this-much/",
            hasOverviewVideo: false,
            isMeterLocked: false,
            isPremiumLocked: false,
            lessonNodeAction: "JUMP_AHEAD_LOCKED",
            lessonNodeStatus: "NOT_STARTED",
            lessonVersionName: null,
            nextPracticeSlug: "splitting-and-combining-1",
            gatingLevelCheck: null,
          },
          {
            __typename: "GameboardLessonNode",
            lessonSlug: "equal-nths",
            nodeKey: "equal-nths",
            title: "Equal Parts",
            contentUrl:
              "/courses/math-fundamentals/mt-fractions-intro/equal-nths/",
            hasOverviewVideo: false,
            isMeterLocked: false,
            isPremiumLocked: false,
            lessonNodeAction: "JUMP_AHEAD_LOCKED",
            lessonNodeStatus: "NOT_STARTED",
            lessonVersionName: null,
            nextPracticeSlug: "equal-parts-1",
            gatingLevelCheck: null,
          },
          {
            __typename: "GameboardLevelCheckNode",
            nodeKey: "math-fundamentals-level-1-check-1",
            title: "Level Check",
            hasOverviewVideo: false,
            isMeterLocked: false,
            isPremiumLocked: false,
            contentUrl:
              "/courses/math-fundamentals/mt-fractions-intro/level-check/math-fundamentals-level-1-check-1/",
            practiceSlug: "math-fundamentals-level-1-check-1",
            numPreviousAttempts: 0,
            levelCheckNodeStatus: "NOT_STARTED",
            levelCheckNodeAction: "JUMP_AHEAD_LOCKED",
          },
        ],
        hideNameAndDescription: false,
        percentComplete: 1,
      },
      {
        __typename: "GameboardLevel",
        slug: "equivalent-fractions",
        contentAccessStatus: "AVAILABLE",
        name: "Equivalent Fractions",
        descriptionBullet1:
          "Express the same fraction of a shape in different ways.",
        descriptionBullet2: null,
        nodesV2: [
          {
            __typename: "GameboardLessonNode",
            lessonSlug: "equal-fractions",
            nodeKey: "equal-fractions",
            title: "Sixths and Twelfths",
            contentUrl:
              "/courses/math-fundamentals/equivalent-fractions/equal-fractions/",
            hasOverviewVideo: false,
            isMeterLocked: false,
            isPremiumLocked: false,
            lessonNodeAction: "JUMP_AHEAD_LOCKED",
            lessonNodeStatus: "NOT_STARTED",
            lessonVersionName: null,
            nextPracticeSlug: "final-six-tw-1-1-EsUZsr-6",
            gatingLevelCheck: null,
          },
          {
            __typename: "GameboardLessonNode",
            lessonSlug: "equal-fractions-2",
            nodeKey: "equal-fractions-2",
            title: "Eighths and Sixteenths",
            contentUrl:
              "/courses/math-fundamentals/equivalent-fractions/equal-fractions-2/",
            hasOverviewVideo: false,
            isMeterLocked: false,
            isPremiumLocked: false,
            lessonNodeAction: "JUMP_AHEAD_LOCKED",
            lessonNodeStatus: "NOT_STARTED",
            lessonVersionName: null,
            nextPracticeSlug: "final-eig-sixt-3-1-BshT6eC6",
            gatingLevelCheck: null,
          },
          {
            __typename: "GameboardLessonNode",
            lessonSlug: "making-equivalent",
            nodeKey: "making-equivalent",
            title: "Making Equivalent Fractions",
            contentUrl:
              "/courses/math-fundamentals/equivalent-fractions/making-equivalent/",
            hasOverviewVideo: false,
            isMeterLocked: false,
            isPremiumLocked: false,
            lessonNodeAction: "JUMP_AHEAD_LOCKED",
            lessonNodeStatus: "NOT_STARTED",
            lessonVersionName: null,
            nextPracticeSlug: "making-equivalent-1-V8hND7YT",
            gatingLevelCheck: null,
          },
          {
            __typename: "GameboardLessonNode",
            lessonSlug: "simplifying-fractions",
            nodeKey: "simplifying-fractions",
            title: "Simplifying Fractions",
            contentUrl:
              "/courses/math-fundamentals/equivalent-fractions/simplifying-fractions/",
            hasOverviewVideo: false,
            isMeterLocked: false,
            isPremiumLocked: false,
            lessonNodeAction: "JUMP_AHEAD_LOCKED",
            lessonNodeStatus: "NOT_STARTED",
            lessonVersionName: null,
            nextPracticeSlug: "final-simp-1-1-hWrqJT3I",
            gatingLevelCheck: null,
          },
          {
            __typename: "GameboardLessonNode",
            lessonSlug: "equivalent-fractions-3",
            nodeKey: "equivalent-fractions-3",
            title: "Equivalent Fractions",
            contentUrl:
              "/courses/math-fundamentals/equivalent-fractions/equivalent-fractions-3/",
            hasOverviewVideo: false,
            isMeterLocked: false,
            isPremiumLocked: false,
            lessonNodeAction: "JUMP_AHEAD_LOCKED",
            lessonNodeStatus: "NOT_STARTED",
            lessonVersionName: null,
            nextPracticeSlug: "og-eq-f-UDjfmsMQ-2-1-VBdLqRJo",
            gatingLevelCheck: null,
          },
          {
            __typename: "GameboardLessonNode",
            lessonSlug: "wodb-equivalents",
            nodeKey: "wodb-equivalents",
            title: "Identifying Equivalents",
            contentUrl:
              "/courses/math-fundamentals/equivalent-fractions/wodb-equivalents/",
            hasOverviewVideo: false,
            isMeterLocked: false,
            isPremiumLocked: false,
            lessonNodeAction: "JUMP_AHEAD_LOCKED",
            lessonNodeStatus: "NOT_STARTED",
            lessonVersionName: null,
            nextPracticeSlug: "og-id-eq-h251l6kb",
            gatingLevelCheck: null,
          },
          {
            __typename: "GameboardLevelCheckNode",
            nodeKey: "math-fundamentals-level-2-check-4",
            title: "Level Check",
            hasOverviewVideo: false,
            isMeterLocked: false,
            isPremiumLocked: false,
            contentUrl:
              "/courses/math-fundamentals/equivalent-fractions/level-check/math-fundamentals-level-2-check-4/",
            practiceSlug: "math-fundamentals-level-2-check-4",
            numPreviousAttempts: 0,
            levelCheckNodeStatus: "NOT_STARTED",
            levelCheckNodeAction: "JUMP_AHEAD_LOCKED",
          },
        ],
        hideNameAndDescription: false,
        percentComplete: 0,
      },
      {
        __typename: "GameboardLevel",
        slug: "comparing-fractions",
        contentAccessStatus: "AVAILABLE",
        name: "Comparing Fractions",
        descriptionBullet1: "Decide which fraction is greater.",
        descriptionBullet2: null,
        nodesV2: [
          {
            __typename: "GameboardLessonNode",
            lessonSlug: "comparing-numerators",
            nodeKey: "comparing-numerators",
            title: "Comparing Numerators",
            contentUrl:
              "/courses/math-fundamentals/comparing-fractions/comparing-numerators/",
            hasOverviewVideo: false,
            isMeterLocked: false,
            isPremiumLocked: false,
            lessonNodeAction: "JUMP_AHEAD_LOCKED",
            lessonNodeStatus: "NOT_STARTED",
            lessonVersionName: null,
            nextPracticeSlug: "comparing-numerators-1",
            gatingLevelCheck: null,
          },
          {
            __typename: "GameboardLessonNode",
            lessonSlug: "same-numerator",
            nodeKey: "same-numerator",
            title: "Comparing Denominators",
            contentUrl:
              "/courses/math-fundamentals/comparing-fractions/same-numerator/",
            hasOverviewVideo: false,
            isMeterLocked: false,
            isPremiumLocked: false,
            lessonNodeAction: "JUMP_AHEAD_LOCKED",
            lessonNodeStatus: "NOT_STARTED",
            lessonVersionName: null,
            nextPracticeSlug: "same-numerator-1-1-1--W-x6T8T",
            gatingLevelCheck: null,
          },
          {
            __typename: "GameboardLessonNode",
            lessonSlug: "den-multiples",
            nodeKey: "den-multiples",
            title: "Comparing Equivalents",
            contentUrl:
              "/courses/math-fundamentals/comparing-fractions/den-multiples/",
            hasOverviewVideo: false,
            isMeterLocked: false,
            isPremiumLocked: false,
            lessonNodeAction: "JUMP_AHEAD_LOCKED",
            lessonNodeStatus: "NOT_STARTED",
            lessonVersionName: null,
            nextPracticeSlug: "den-multiples-1",
            gatingLevelCheck: null,
          },
          {
            __typename: "GameboardLessonNode",
            lessonSlug: "not-multiples",
            nodeKey: "not-multiples",
            title: "Comparing More Equivalents",
            contentUrl:
              "/courses/math-fundamentals/comparing-fractions/not-multiples/",
            hasOverviewVideo: false,
            isMeterLocked: false,
            isPremiumLocked: false,
            lessonNodeAction: "JUMP_AHEAD_LOCKED",
            lessonNodeStatus: "NOT_STARTED",
            lessonVersionName: null,
            nextPracticeSlug: "not-multiples-3-1-1F7HW7uA",
            gatingLevelCheck: null,
          },
          {
            __typename: "GameboardLessonNode",
            lessonSlug: "greatest-fraction",
            nodeKey: "greatest-fraction",
            title: "Identifying the Greatest",
            contentUrl:
              "/courses/math-fundamentals/comparing-fractions/greatest-fraction/",
            hasOverviewVideo: false,
            isMeterLocked: false,
            isPremiumLocked: false,
            lessonNodeAction: "JUMP_AHEAD_LOCKED",
            lessonNodeStatus: "NOT_STARTED",
            lessonVersionName: null,
            nextPracticeSlug: "greatest-fraction-practice",
            gatingLevelCheck: null,
          },
        ],
        hideNameAndDescription: false,
        percentComplete: 0,
      },
      {
        __typename: "GameboardLevel",
        slug: "adding-fractions",
        contentAccessStatus: "AVAILABLE",
        name: "Adding Fractions",
        descriptionBullet1: "Add and subtract parts of a shape.",
        descriptionBullet2: null,
        nodesV2: [
          {
            __typename: "GameboardLessonNode",
            lessonSlug: "adding-fractions",
            nodeKey: "adding-fractions",
            title: "Adding Fractions",
            contentUrl:
              "/courses/math-fundamentals/adding-fractions/adding-fractions/",
            hasOverviewVideo: false,
            isMeterLocked: false,
            isPremiumLocked: false,
            lessonNodeAction: "JUMP_AHEAD_LOCKED",
            lessonNodeStatus: "NOT_STARTED",
            lessonVersionName: null,
            nextPracticeSlug: "adding-fractions-practice-5-1-dCZ3TxLx",
            gatingLevelCheck: null,
          },
          {
            __typename: "GameboardLessonNode",
            lessonSlug: "add-unit-fractions",
            nodeKey: "add-unit-fractions",
            title: "Adding Same-Sized Fractions",
            contentUrl:
              "/courses/math-fundamentals/adding-fractions/add-unit-fractions/",
            hasOverviewVideo: false,
            isMeterLocked: false,
            isPremiumLocked: false,
            lessonNodeAction: "JUMP_AHEAD_LOCKED",
            lessonNodeStatus: "NOT_STARTED",
            lessonVersionName: null,
            nextPracticeSlug: "add-unit-fractions-practice",
            gatingLevelCheck: null,
          },
          {
            __typename: "GameboardLessonNode",
            lessonSlug: "adding-different",
            nodeKey: "adding-different",
            title: "Adding Unlike Parts",
            contentUrl:
              "/courses/math-fundamentals/adding-fractions/adding-different/",
            hasOverviewVideo: false,
            isMeterLocked: false,
            isPremiumLocked: false,
            lessonNodeAction: "JUMP_AHEAD_LOCKED",
            lessonNodeStatus: "NOT_STARTED",
            lessonVersionName: null,
            nextPracticeSlug: "adding-different-2",
            gatingLevelCheck: null,
          },
          {
            __typename: "GameboardLessonNode",
            lessonSlug: "adding-nonmultiples",
            nodeKey: "adding-nonmultiples",
            title: "Adding Unit Fractions",
            contentUrl:
              "/courses/math-fundamentals/adding-fractions/adding-nonmultiples/",
            hasOverviewVideo: false,
            isMeterLocked: false,
            isPremiumLocked: false,
            lessonNodeAction: "JUMP_AHEAD_LOCKED",
            lessonNodeStatus: "NOT_STARTED",
            lessonVersionName: null,
            nextPracticeSlug: "adding-nonmultiples-2",
            gatingLevelCheck: null,
          },
          {
            __typename: "GameboardLessonNode",
            lessonSlug: "adding-unlike",
            nodeKey: "adding-unlike",
            title: "Adding Any Fractions",
            contentUrl:
              "/courses/math-fundamentals/adding-fractions/adding-unlike/",
            hasOverviewVideo: false,
            isMeterLocked: false,
            isPremiumLocked: false,
            lessonNodeAction: "JUMP_AHEAD_LOCKED",
            lessonNodeStatus: "NOT_STARTED",
            lessonVersionName: null,
            nextPracticeSlug: "adding-unlike-1",
            gatingLevelCheck: null,
          },
        ],
        hideNameAndDescription: false,
        percentComplete: 0,
      },
      {
        __typename: "GameboardLevel",
        slug: "multiplying-fractions",
        contentAccessStatus: "AVAILABLE",
        name: "Multiplying Fractions",
        descriptionBullet1:
          "What does it mean to multiply fractions, and how can we multiply them mentally?",
        descriptionBullet2: null,
        nodesV2: [
          {
            __typename: "GameboardLessonNode",
            lessonSlug: "fraction-by-integer",
            nodeKey: "fraction-by-integer",
            title: "Multiples of Fractions",
            contentUrl:
              "/courses/math-fundamentals/multiplying-fractions/fraction-by-integer/",
            hasOverviewVideo: false,
            isMeterLocked: false,
            isPremiumLocked: false,
            lessonNodeAction: "JUMP_AHEAD_LOCKED",
            lessonNodeStatus: "NOT_STARTED",
            lessonVersionName: null,
            nextPracticeSlug: "fraction-by-integer-1-3-1-SITa2h_E",
            gatingLevelCheck: null,
          },
          {
            __typename: "GameboardLessonNode",
            lessonSlug: "expressing-multiples",
            nodeKey: "expressing-multiples",
            title: "Expressing Multiples",
            contentUrl:
              "/courses/math-fundamentals/multiplying-fractions/expressing-multiples/",
            hasOverviewVideo: false,
            isMeterLocked: false,
            isPremiumLocked: false,
            lessonNodeAction: "JUMP_AHEAD_LOCKED",
            lessonNodeStatus: "NOT_STARTED",
            lessonVersionName: null,
            nextPracticeSlug: "expressing-multiples-1-2-1-dV95fO9e",
            gatingLevelCheck: null,
          },
          {
            __typename: "GameboardLessonNode",
            lessonSlug: "fractions-of-fractions",
            nodeKey: "fractions-of-fractions",
            title: "Fractions of Unit Fractions",
            contentUrl:
              "/courses/math-fundamentals/multiplying-fractions/fractions-of-fractions/",
            hasOverviewVideo: false,
            isMeterLocked: false,
            isPremiumLocked: false,
            lessonNodeAction: "JUMP_AHEAD_LOCKED",
            lessonNodeStatus: "NOT_STARTED",
            lessonVersionName: null,
            nextPracticeSlug: "fractions-of-fractions-practice",
            gatingLevelCheck: null,
          },
          {
            __typename: "GameboardLessonNode",
            lessonSlug: "expressing-fouf",
            nodeKey: "expressing-fouf",
            title: "Products of Unit Fractions",
            contentUrl:
              "/courses/math-fundamentals/multiplying-fractions/expressing-fouf/",
            hasOverviewVideo: false,
            isMeterLocked: false,
            isPremiumLocked: false,
            lessonNodeAction: "JUMP_AHEAD_LOCKED",
            lessonNodeStatus: "NOT_STARTED",
            lessonVersionName: null,
            nextPracticeSlug: "expressing-fouf-practice",
            gatingLevelCheck: null,
          },
          {
            __typename: "GameboardLessonNode",
            lessonSlug: "fractions-of-fractions-2",
            nodeKey: "fractions-of-fractions-2",
            title: "Fraction of Any Fraction",
            contentUrl:
              "/courses/math-fundamentals/multiplying-fractions/fractions-of-fractions-2/",
            hasOverviewVideo: false,
            isMeterLocked: false,
            isPremiumLocked: false,
            lessonNodeAction: "JUMP_AHEAD_LOCKED",
            lessonNodeStatus: "NOT_STARTED",
            lessonVersionName: null,
            nextPracticeSlug: "fractions-of-fractions-2-practice",
            gatingLevelCheck: null,
          },
          {
            __typename: "GameboardLessonNode",
            lessonSlug: "multiplying-fractions",
            nodeKey: "multiplying-fractions",
            title: "Multiplying Fractions",
            contentUrl:
              "/courses/math-fundamentals/multiplying-fractions/multiplying-fractions/",
            hasOverviewVideo: false,
            isMeterLocked: false,
            isPremiumLocked: false,
            lessonNodeAction: "JUMP_AHEAD_LOCKED",
            lessonNodeStatus: "NOT_STARTED",
            lessonVersionName: null,
            nextPracticeSlug: "multiplying-fractions-practice",
            gatingLevelCheck: null,
          },
        ],
        hideNameAndDescription: false,
        percentComplete: 0,
      },
    ],
    currentNodeKey: "find-half",
    personalizedPractice: {
      __typename: "PersonalizedPracticeSet",
      availability: "PREMIUM_REQUIRED",
      isCompleted: false,
      practiceSetSlug: null,
      source: "PERSONALIZED",
      chapterSlug: null,
      versionName: null,
    },
  },
  learningPathContext: {
    __typename: "CourseLearningPathContext",
    learningPath: {
      __typename: "LearningPath",
      id: "R7ZxQLlAeLb0v7vb88ATmTeZz",
      colorScheme: {
        __typename: "ColorScheme",
        s300: "#ABBDFF",
      },
      slug: "foundational-math",
    },
    nextCourse: {
      __typename: "Course",
      slug: "pre-algebra",
      title: "Solving Equations",
      introText:
        "Start your algebra journey here with an introduction to variables and equations.",
      desktopOnly: false,
      premiumOnly: false,
      lessonCount: 68,
    },
  },
  collaborators: [],
  desktopOnly: false,
  introText: "Learn to wield important tools in number sense and computation.",
  percentComplete: 1,
  premiumOnly: false,
  lessonCount: 27,
  exerciseCount: 375,
  retiringOn: null,
  conceptsInclude: [
    "Fraction comparison",
    "Equivalent fractions",
    "Adding and subtracting fractions",
    "Multiplying fractions",
  ],
  prereqAndNextStepNotes:
    "This course is for anyone ready for a refresher and new challenges on core numerical concepts.",
  prerequisites: [],
  nextSteps: [
    {
      __typename: "Course",
      absoluteUrl: "/courses/puzzle-science/",
      title: "Scientific Thinking",
    },
  ],
  previouslyEnrolled: true,
};
